import { supabaseAdmin } from '../config/supabase';
import { Complaint, ComplaintUpdate } from '../types';

/**
 * Create a new complaint (public — no auth required).
 * Complaint number is auto-generated by the database trigger.
 */
export async function createComplaint(complaint: {
  name: string;
  mobile: string;
  area: string;
  complaint_type: string;
  description?: string;
}): Promise<Complaint> {
  const { data, error } = await supabaseAdmin
    .from('complaints')
    .insert({
      name: complaint.name,
      mobile: complaint.mobile,
      area: complaint.area,
      complaint_type: complaint.complaint_type,
      description: complaint.description || null,
    })
    .select()
    .single();

  if (error) {
    console.error('[Complaint] Failed to create:', error);
    throw new Error('Failed to register complaint');
  }

  return data;
}

/**
 * Get all complaints with optional status filter.
 */
export async function getAllComplaints(status?: string): Promise<Complaint[]> {
  let query = supabaseAdmin
    .from('complaints')
    .select('*')
    .order('created_at', { ascending: false });

  if (status && status !== 'all') {
    query = query.eq('status', status);
  }

  const { data, error } = await query;

  if (error) throw new Error('Failed to fetch complaints');
  return data || [];
}

/**
 * Get a single complaint by ID with its update history.
 */
export async function getComplaintById(id: string): Promise<{
  complaint: Complaint;
  updates: ComplaintUpdate[];
} | null> {
  const { data: complaint, error } = await supabaseAdmin
    .from('complaints')
    .select('*')
    .eq('id', id)
    .single();

  if (error || !complaint) return null;

  const { data: updates } = await supabaseAdmin
    .from('complaint_updates')
    .select('*')
    .eq('complaint_id', id)
    .order('updated_at', { ascending: false });

  return { complaint, updates: updates || [] };
}

/**
 * Update complaint status and add a remark.
 */
export async function updateComplaintStatus(
  complaintId: string,
  status: string,
  remark: string | null,
  updatedBy: string
): Promise<Complaint> {
  // Update the complaint status
  const { data: complaint, error: updateError } = await supabaseAdmin
    .from('complaints')
    .update({ status })
    .eq('id', complaintId)
    .select()
    .single();

  if (updateError) throw new Error('Failed to update complaint');

  // Insert update record for audit trail
  const { error: insertError } = await supabaseAdmin
    .from('complaint_updates')
    .insert({
      complaint_id: complaintId,
      status,
      remark: remark || null,
      updated_by: updatedBy,
    });

  if (insertError) {
    console.error('[Complaint] Failed to insert update record:', insertError);
  }

  return complaint;
}

/**
 * Get complaint counts by status.
 */
export async function getComplaintCounts(): Promise<{
  total: number;
  new: number;
  in_progress: number;
  resolved: number;
}> {
  const { data, error } = await supabaseAdmin
    .from('complaints')
    .select('status');

  if (error || !data) {
    return { total: 0, new: 0, in_progress: 0, resolved: 0 };
  }

  return {
    total: data.length,
    new: data.filter((c) => c.status === 'new').length,
    in_progress: data.filter((c) => c.status === 'in_progress').length,
    resolved: data.filter((c) => c.status === 'resolved').length,
  };
}

/**
 * Get count of new complaints (for dashboard KPI).
 */
export async function getNewComplaintCount(): Promise<number> {
  const { count, error } = await supabaseAdmin
    .from('complaints')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'new');

  if (error) return 0;
  return count || 0;
}
